spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo_db?serverTimezone=UTC
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  error:
    include-stacktrace: never